### ISSUE TITLE
led_on and led_off

### ISSUE THREAD

**Issue by mahesh2000** [SensorsIot/ESP32-ULP-Arduino-IDE#2]
hi, i don't see led_on and led_off being used anywhere. do you have an example of where they work? i want the ulp to wake every 2 seconds, flash the led, get an adc reading and go to sleep. it shouldn't wake up the main core(s). 

also, by merely including the `led_on` and `led_off` code sections, i get the following compilation errors:

```
C:\Users\mahes\Documents\ArduinoData\packages\esp32\tools\ulptool\src/esp32ulp-elf-binutils/bin/esp32ulp-elf-as -al=adc.ulp.lst -W -o adc.ulp.o adc.ulp.pS
config/tc-esp32ulp.c:1042:Unknown node expression found during arithmetic relocation generationconfig/tc-esp32ulp.c:1042:Unknown node expression found during arithmetic relocation generationconfig/tc-esp32ulp.c:1042:Unknown node expression found during arithmetic relocation generationconfig/tc-esp32ulp.c:1042:Unknown node expression found during arithmetic relocation generationconfig/tc-esp32ulp.c:1042:Unknown node expression found during arithmetic relocation generationconfig/tc-esp32ulp.c:1042:Unknown node expression found during arithmetic relocation generation

exit status 1
Error compiling for board ESP32 Dev Module.
```

**Comment by SensorsIot** [comment]
Maybe you go to the ulp Github repository (https://github.com/duff2013/ulptool ). There have been changes since the video.

**Comment by mahesh2000** [comment]
hi, i received the errors because i didn't include a header file. it also appears that the on-board LED (GPIO16)  cannot be controlled by the ULP; i need to connect an external. thanks for a nice video :)

**Comment by mahesh2000** [comment]
my on-board LED is connected to GPIO16; when the pin goes LOW, the LED turns on. so it must be tied HIGH. i'm going to tie GPIO16 to GPIO2 (RTCIO12). if i can set RTCIO12 LOW and have the LED turn on, i reduce my component count :-). i'll let you know how it goes.

```
Vcc
  |
  |----|>----/\/\/\/\---- Vcc
          |
          |--- GPIO16
          |--- GPIO2/RTCIO12 **connect this**


```

**Comment by mahesh2000** [comment]
i got it working; i've put up a simple test project at https://github.com/mahesh2000/ESP32_ulp_blink.
